name: Lint

on:
  push:
      branches: [ "main", "dev" ]
  pull_request:
      branches: [ "main", "dev" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrdivyansh/eslint-action@v1.0.7